# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.ManyToManyField(help_text='Исрользовать ссылки', null=True, to='facebot.Urls'),
        ),
    ]
