# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0002_auto_20171111_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='momentforwork',
            field=models.TimeField(help_text='Время публикации, ЧЧ:ММ:СС', max_length=25, verbose_name='Время'),
        ),
    ]
