# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0003_auto_20171111_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_run',
            field=models.DateTimeField(help_text='Дата и время очередного запуска', max_length=25, null=True, verbose_name='Время запуска'),
        ),
    ]
