# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0004_task_time_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя папки', max_length=120, unique=True, verbose_name='Имя')),
                ('description', models.CharField(max_length=120, verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='time_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='momentforwork',
            field=models.TimeField(help_text='Время следущей публикации, ЧЧ:ММ:СС', max_length=25, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='task',
            name='periodpublic',
            field=models.CharField(choices=[('0', 'один раз'), ('1', 'один раз в 1 минуту'), ('20', 'один раз в минуту')], default='one', max_length=25, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_run',
            field=models.DateTimeField(blank=True, help_text='Дата и время очередного запуска', max_length=25, null=True, verbose_name='Время запуска'),
        ),
    ]
