# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0005_auto_20171114_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя папки', max_length=120, null=True, unique=True, verbose_name='Имя')),
                ('description', models.DateTimeField(max_length=120, null=True, verbose_name='Период')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='catalog',
            field=models.ForeignKey(help_text='Каталог на диске', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facebot.Folders'),
        ),
        migrations.AddField(
            model_name='task',
            name='peripd_pub',
            field=models.ForeignKey(help_text='Период публикации', null=True, on_delete=django.db.models.deletion.CASCADE, to='facebot.Period'),
        ),
    ]
