# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0006_auto_20171115_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='description',
        ),
        migrations.AddField(
            model_name='period',
            name='days',
            field=models.DecimalField(decimal_places=0, help_text='Количество дней', max_digits=2, null=True, verbose_name='Дни'),
        ),
        migrations.AddField(
            model_name='period',
            name='hour',
            field=models.DecimalField(decimal_places=0, help_text='Количество часов', max_digits=2, null=True, verbose_name='Часы'),
        ),
        migrations.AddField(
            model_name='period',
            name='minutes',
            field=models.DecimalField(decimal_places=0, help_text='Количество минут', max_digits=2, null=True, verbose_name='Минуты'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='Имя'),
        ),
    ]
