# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0008_auto_20171117_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='days',
            field=models.IntegerField(help_text='Количество дней', null=True, verbose_name='Дни'),
        ),
        migrations.AlterField(
            model_name='period',
            name='hour',
            field=models.IntegerField(help_text='Количество часов', null=True, verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='period',
            name='minutes',
            field=models.IntegerField(help_text='Количество минут', null=True, verbose_name='Минуты'),
        ),
    ]
