# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0010_auto_20171117_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='period_pub',
        ),
        migrations.AddField(
            model_name='task',
            name='peripd_pub',
            field=models.ForeignKey(help_text='Период публикации', null=True, on_delete=django.db.models.deletion.CASCADE, to='facebot.Period'),
        ),
    ]
