# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0011_auto_20171117_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_period',
            field=models.DurationField(null=True),
        ),
    ]
