# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0013_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='momentforwork',
            field=models.TimeField(help_text='Время следущей публикации, ЧЧ:ММ:СС', max_length=25, null=True, verbose_name='Время'),
        ),
    ]
