# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0014_auto_20171130_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['chanelforpublic']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='momentforwork',
        ),
        migrations.RemoveField(
            model_name='task',
            name='peripd_pub',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_run',
        ),
    ]
