# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0015_auto_20171130_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(blank=True, choices=[('GIF', 'Гифки'), ('TXT', 'Тескс Markdown'), ('PNG', 'Картинки')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='filetypesforload',
        ),
        migrations.AddField(
            model_name='task',
            name='filetypesforload',
            field=models.ManyToManyField(null=True, to='facebot.FileTypeChoices'),
        ),
    ]
