# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0016_auto_20171202_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetypechoices',
            name='options',
        ),
        migrations.AddField(
            model_name='filetypechoices',
            name='desc',
            field=models.CharField(help_text='Описание', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='filetypechoices',
            name='ftype',
            field=models.CharField(help_text='расширение без точки', max_length=120, null=True, unique=True),
        ),
    ]
