# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0017_auto_20171202_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='caption',
            field=models.CharField(blank=True, max_length=120, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.ManyToManyField(blank=True, help_text='Исрользовать ссылки', null=True, to='facebot.Urls'),
        ),
    ]
