# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0018_auto_20171203_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcesdata',
            name='login',
        ),
        migrations.RemoveField(
            model_name='sourcesdata',
            name='password',
        ),
        migrations.RemoveField(
            model_name='sourcesdata',
            name='urls',
        ),
        migrations.AddField(
            model_name='sourcesdata',
            name='token',
            field=models.CharField(help_text='отладочный токен ядиска', max_length=50, null=True, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='sourcesdata',
            name='sourcename',
            field=models.CharField(help_text='Произвольное имя источника', max_length=25, null=True, unique=True, verbose_name='Имя'),
        ),
    ]
