# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0019_auto_20171204_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesdata',
            name='token',
            field=models.CharField(help_text='отладочный токен ядиска', max_length=50, null=True, verbose_name='Токен'),
        ),
    ]
