# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0020_auto_20171218_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='catalog_ajax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Каталог на диске'),
        ),
    ]
