# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebot', '0022_auto_20171227_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanels',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
