# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0024_auto_20180111_0212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reactioan',
        ),
        migrations.AlterField(
            model_name='mybot',
            name='botname',
            field=models.CharField(help_text='Имя бота', max_length=120, unique=True, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='mybot',
            name='bottoken',
            field=models.CharField(help_text='Токен бота', max_length=120, unique=True, verbose_name='Токен бота'),
        ),
    ]
