# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0026_auto_20180128_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='task',
        ),
        migrations.AddField(
            model_name='shedule',
            name='task',
            field=models.ForeignKey(help_text='Задача для выполнения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facebot.Task'),
        ),
    ]
