# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0027_auto_20180129_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='task',
        ),
        migrations.AddField(
            model_name='shedule',
            name='task',
            field=models.ManyToManyField(help_text='Задача для выполнения', null=True, to='facebot.Task'),
        ),
    ]
