# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0028_auto_20180129_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='numfileforpub_random',
            field=models.NullBooleanField(verbose_name='Случайно'),
        ),
    ]
