# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0029_task_numfileforpub_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='numfileforpub_random',
            field=models.BooleanField(default=False, verbose_name='Случайно'),
        ),
    ]
