# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0030_auto_20180204_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num_file_max',
            field=models.IntegerField(null=True, verbose_name='Максимальное количесто публикуемых файлов'),
        ),
        migrations.AddField(
            model_name='task',
            name='num_file_min',
            field=models.IntegerField(null=True, verbose_name='Минимальное количесто публикуемых файлов'),
        ),
    ]
