# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0031_auto_20180204_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='numfileforpub_random',
            field=models.BooleanField(default=True, verbose_name='Случайно'),
        ),
    ]
