# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0033_auto_20180204_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='num_file_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количесто публикуемых файлов'),
        ),
        migrations.AlterField(
            model_name='task',
            name='num_file_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальное количесто публикуемых файлов'),
        ),
        migrations.AlterField(
            model_name='task',
            name='numfileforpub_random',
            field=models.BooleanField(choices=[(True, ' Случайно'), (False, 'Вручную')], default=False, verbose_name='Случайно'),
        ),
    ]
