# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebot', '0036_auto_20180205_0344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('taskname', 'created_by')]),
        ),
    ]
