# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0037_auto_20180211_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskname',
            field=models.CharField(max_length=25, verbose_name='Имя задачи'),
        ),
    ]
