# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0039_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Имя задачи')),
                ('imgs', models.ImageField(default='pic_folder/no-img.png', upload_to='pic_folder/')),
                ('text', models.CharField(help_text='Описание', max_length=600, verbose_name='Описание')),
            ],
        ),
    ]
