# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebot', '0044_auto_20180212_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanels',
            name='chanelname',
            field=models.CharField(help_text='Имя канала', max_length=25, verbose_name='Имя канала'),
        ),
        migrations.AlterField(
            model_name='mybot',
            name='botname',
            field=models.CharField(help_text='Имя бота', max_length=120, verbose_name='Имя бота'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='name',
            field=models.CharField(help_text='Уникальное имя', max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sourcesdata',
            name='sourcename',
            field=models.CharField(help_text='Произвольное имя источника', max_length=25, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='urlname',
            field=models.CharField(help_text='Имя ссылки', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='chanels',
            unique_together=set([('chanelname', 'created_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='mybot',
            unique_together=set([('botname', 'created_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='shedule',
            unique_together=set([('name', 'created_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='sourcesdata',
            unique_together=set([('sourcename', 'created_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='urls',
            unique_together=set([('urlname', 'created_by')]),
        ),
    ]
