# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facebot', '0045_auto_20180213_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybot',
            name='bottoken',
            field=models.CharField(help_text='Токен бота', max_length=120, verbose_name='Токен бота'),
        ),
        migrations.AlterUniqueTogether(
            name='mybot',
            unique_together=set([('botname', 'created_by', 'bottoken')]),
        ),
    ]
