# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0047_oncetask_del_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncetask',
            name='status',
            field=models.CharField(default='не известно', max_length=25, verbose_name='Статус'),
        ),
    ]
