# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0048_oncetask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncetask',
            name='status',
            field=models.CharField(max_length=25, null=True, verbose_name='Статус'),
        ),
    ]
