# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0049_auto_20180217_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncetask',
            name='type_mes',
            field=models.CharField(choices=[('text', ' Текст'), ('photo', 'Картинка с подписью')], default='text', max_length=10, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='oncetask',
            name='text',
            field=models.CharField(help_text='Описание', max_length=6000, verbose_name='Описание'),
        ),
    ]
