# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0050_auto_20180218_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oncetask',
            name='chanelforpublic',
        ),
        migrations.AddField(
            model_name='oncetask',
            name='chanelforpublic',
            field=models.ManyToManyField(help_text='Канал для публикации', null=True, to='facebot.Chanels'),
        ),
    ]
