# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0054_remove_oncetask_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='picture',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='model_pic',
            field=models.ImageField(null=True, upload_to='pic_folder/'),
        ),
    ]
