# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0056_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
