# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0057_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=120, null=True, verbose_name='ид собщения')),
                ('like_count', models.IntegerField(null=True, verbose_name='количество лайков')),
                ('dislike_count', models.IntegerField(null=True, verbose_name='количество лайков')),
            ],
        ),
    ]
