# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0058_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereaction',
            name='chat_id',
            field=models.CharField(max_length=120, null=True, verbose_name='ид чата'),
        ),
    ]
