# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0059_messagereaction_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='chat_id',
            field=models.TextField(max_length=120, null=True, verbose_name='ид чата'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='message_id',
            field=models.TextField(max_length=120, null=True, verbose_name='ид собщения'),
        ),
    ]
