# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0062_profile_ip_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegramm',
            field=models.CharField(blank=True, default='не задано', max_length=20),
        ),
    ]
