# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0064_task_isfiledelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereaction',
            name='chanel_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя канала'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='username',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя пользователя'),
        ),
    ]
