# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0065_auto_20180325_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='datetowork',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
