# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0066_profile_datetowork'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=25, null=True, verbose_name='Статус'),
        ),
    ]
