# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0067_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='datetowork',
            field=models.DateTimeField(null=True),
        ),
    ]
