# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebot', '0069_mesages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesages',
            new_name='Messages',
        ),
    ]
